

ALTER TABLE UTILISATEURS ADD CONSTRAINT CK_UTILISATEURS UNIQUE (pseudo, email);

ALTER TABLE ARTICLES_VENDUS ADD etat_vente INT NOT NULL;

ALTER TABLE UTILISATEURS ALTER COLUMN email VARCHAR(60);

INSERT INTO CATEGORIES VALUES ('Informatique');
INSERT INTO CATEGORIES VALUES ('Ameublement');
INSERT INTO CATEGORIES VALUES ('Vêtement');
INSERT INTO CATEGORIES VALUES ('Sport&Loisirs');

CREATE PROCEDURE maj_etat_vente

as
	UPDATE ARTICLES_VENDUS SET etat_vente='2' WHERE date_debut_encheres<=GETDATE() AND etat_vente ='1'; 
	UPDATE ARTICLES_VENDUS SET etat_vente='3' WHERE date_fin_encheres<GETDATE() AND etat_vente ='2';