

ALTER TABLE UTILISATEURS ADD CONSTRAINT CK_UTILISATEURS UNIQUE (pseudo, email);

ALTER TABLE ARTICLES_VENDUS ADD etat_vente INT NOT NULL;

ALTER TABLE UTILISATEURS ALTER COLUMN email VARCHAR(60);

INSERT INTO CATEGORIES VALUES ('Informatique');
INSERT INTO CATEGORIES VALUES ('Ameublement');
INSERT INTO CATEGORIES VALUES ('Vêtement');
INSERT INTO CATEGORIES VALUES ('Sport&Loisirs');